import DoctorsCard from '@/components/DoctorsCard';
import React from 'react';

export const metadata = {
  title: "All Appointments|DocAppoint",
  description: "Generated by DocAppoint",
};

const AllAppointmentsPage = async() => {
     const res = await fetch(`${process.env.NEXT_PUBLIC_SERVER_URL}/doctor`)
    const doctors = await res.json()
    console.log(doctors)
    return (
        <div className='container mx-auto mb-20'>
           <h1>All Appoinments</h1>

            <div className='grid grid-cols-1 md:grid-cols-2  lg:grid-cols-3 gap-5 '>
                {
                    doctors.map(doctor => <DoctorsCard key={doctor._id}
                    doctor={doctor}></DoctorsCard>)
                }
            </div> 
        </div>
    );
};

export default AllAppointmentsPage;