// src/app/dashboard/layout.jsx

export const metadata = {
  title: "Dashboard | DocAppoint",
  description: "Generated by DocAppoint",
};

export default function DashboardLayout({ children }) {
  return (
    <section className="w-full min-h-screen bg-white">
      {children}
    </section>
  );
}